### ISSUE TITLE
mzTab for DIA-NN

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#119]
### Description of feature

DIA-NN results are not only exported to MSstats, we need to be able to export the results to mzTab.

**Comment by WangHong007** [comment]
When converting the results of DIANN to mzTab, some columns are missing in three levels.

1. MTD

- `protein_search_engine_score[1]`
- `peptide_search_engine_score[1]`
- `psm_search_engine_score[1]`
- `software[1]`

2. RPH
- `protein_coverage`

3. PEH
- `retention_time_window`
- `spectra_ref`
- `opt_global_feature_id`

4. PSH
- `calc_mass_to_charge`
- `pre`
- `post`
- `start`
- `end`
- `spectra_ref`
- `opt_global_spectrum_reference`
- `opt_global_feature_id`
- `opt_global_map_index`

**Comment by ypriverol** [comment]
> When converting the results of DIANN to mzTab, some columns are missing in three levels.
> 
> 1. MTD
> 
> * `protein_search_engine_score[1]`
> * `peptide_search_engine_score[1]`
> * `psm_search_engine_score[1]`
> * `software[1]`

This is related with the following issue https://github.com/vdemichev/DiaNN/issues/362 We first need to decided which one will be the best scores from DIANN, add them in PSI-MS and the use them in mzTab export. 

> 
> 2. RPH
> 
> * `protein_coverage`

> 
> 3. PEH
> 
> * `retention_time_window`
> * `spectra_ref`
> * `opt_global_feature_id`
> 
> 4. PSH
> 
> * `calc_mass_to_charge`
> * `pre`
> * `post`
> * `start`
> * `end`
> * `spectra_ref`
> * `opt_global_spectrum_reference`
> * `opt_global_feature_id`
> * `opt_global_map_index`

**Comment by timosachsenberg** [comment]
I think null is fine here

**Comment by WangHong007** [comment]
Remaining issues

1. MTD
Wait for the following data to be added in OLS, here vdemichev/DiaNN#362
`protein_search_engine_score[1]`
`peptide_search_engine_score[1]`
`psm_search_engine_score[1]`
`software[1]`

2. PEH
This is related with the following issue vdemichev/DiaNN#350
`retention_time_window`
`spectra_ref`

3. PSH
`spectra_ref`
`opt_global_spectrum_reference`

**Comment by vdemichev** [comment]
DIA-NN stores the scan numbers for each precursor, and these are separate for MS2 (note that for both MS1 and MS2 counting scans in DIA-NN is separate and starts with 0). The respective output column is MS2.Scan.

**Comment by ypriverol** [comment]
Thanks for your quick response @vdemichev : 

Do you mean, that the MS2.Scan is basically an index system corresponding to the order of the scan in the RAW/mzML file?

**Comment by vdemichev** [comment]
Yes, but it indexes MS2 scans only. If there's scan, say, 1000, then an MS1 scan, and then another MS2 scan, then this other MS2 scan will have index 1001, not 1002.

**Comment by WangHong007** [comment]
So DIANN counts the scanned precursors and fragments, `MS2.Scan` does not refer to `scan` or `index` in the mzML file? eg. `MS2.scan=73091` in main report doesn't refer to `<spectrum id="controllerType=0 controllerNumber=1 scan=73091" index="73090" defaultArrayLength="441">` in mzML file.

**Comment by vdemichev** [comment]
Yes, it does not refer to the mzML scan number.

Vadim

**Comment by ypriverol** [comment]
For the release of 1.1 we will be exporting only the protein and peptide sections as agreed with @WangHong007. Then, when DIA-NN exports the original scan in the mzML we will export the PSM table.
