### ISSUE TITLE
DIA-NN step before id, generate the library-free 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#125]
### Description of feature

@qinchunyuan the current DIA-NN step contains the library-free generation + the processing step. I think, it would be better to split the current process in two steps: 

1- library generation from fasta database. 
2- perform the analysis using the library previously generated.

**Comment by daichengxin** [comment]
#132

**Comment by jpfeuffer** [comment]
Yes this might speed up a lot since it parallelizes across worker nodes

**Comment by ypriverol** [comment]
Done.
