### ISSUE TITLE
DIA-NN not annotating the protein accessions

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#127]
### Description of feature

Currently, the protein ids are lost from the output. 

```
ProteinName,PeptideSequence,PrecursorCharge,Intensity,Reference,FragmentIon,ProductCharge,IsotopeLabelType,Run,Fraction,BioReplicate,Condition
,AAAQLLQSQAQQSGAQQTK,2,22069.08594,N295-1,NA,0,L,N295-1,1,2,lung
```

Checking in the output file also, you don't find them, looks like is missing in the diann files. Here are some discussions about the protein inference https://github.com/vdemichev/DiaNN/discussions/316

**Comment by daichengxin** [comment]
Are all the proteins Ids missing? Does the log file report error or anomalies?

**Comment by daichengxin** [comment]
#132

**Comment by vdemichev** [comment]
Is there an example log file & output report which shows this?

**Comment by ypriverol** [comment]
@daichengxin do you have a small log file with this error. If not, I can try to reproduce the error in the cluster and share the log. @vdemichev can you let us know with command parameter should be used to debug, verbose the tool. We now have only default messages

**Comment by daichengxin** [comment]
sorry, no more.
