### ISSUE TITLE
DIA-NN improvements. 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#130]
### Description of feature

Today I had a discussion with @vdemichev about DIA-NN in quantms. We discuss multiple topics, I will relate some of them here: 

- [x] conda package of DIA-NN. Currently, the pipeline can we run in **docker** and **singularity**, without access to the source code, the releases only will work for some specific architectures, the ones used by the developer to build the tool. After talking to the bioconda team, we have decided to wait until a user ask for it.   
- [ ] Include some parameters from the dian-nn into the current for those datasets where the information can be annotated, this can help to speed-the process of searching: 
    - [x]  Precursor m/z range. 
    - [x]  Fragment m/z range
    - [x] Relaxed protein inference. In the documentation of the tool, the authors claims that --relaxed-prot-inf can be used for the protein inference and `is faster` than the default method. In quantms we recommend the user of other tools like msstats for downstream analysis which enable consensus results between TMT, LFQ and DIA-LFQ.
- [x] @vdemichev proposed a strategy to use more parallelization in the tool using dia-nn and quantms. The idea is to run on each RAW file independently DIA-NN and generate the libraries from them and also the predicted config files. Then,  in a final search use the libraries from independent searches with all files together and perform MBR etc.

**Comment by jpfeuffer** [comment]
Question: why not use the latest open source version?

**Comment by ypriverol** [comment]
They have improved the tool a lot since that, specially the library prediction, which is crucial in our case. I have tested already the tool in singularity and docker and it works which is good.

**Comment by jpfeuffer** [comment]
Okay 👍

**Comment by daichengxin** [comment]
#132

**Comment by ypriverol** [comment]
Running the new version of the pipeline with `the library generation step` the pipeline fails most of the time. @vdemichev already mentioned that to me that library generation had a bug in Linux archs. I will way for the new release to fix it.
