### ISSUE TITLE
Since DIA-NN is not supported by conda, not the entire pipeline no

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#136]
### Description of the bug

We have a major `bug` @qinchunyuan @jpfeuffer since the DIA-NN message has been added for conda (which I think is great), now the entire pipeline do not work with conda. I guess nextflow doesn't know if the pipeline will go in that branch of the pipeline at the very beginning, then it fails. We need to find a solution.

**Comment by jpfeuffer** [comment]
see also my comments in the release PR. I found that too

**Comment by jpfeuffer** [comment]
We probably should fail in the SDRF checking process if we find it is a DIA SDRF and conda was enabled.

**Comment by jpfeuffer** [comment]
See also https://nfcore.slack.com/archives/CE6SDBX2A/p1648043781319729
for some suggestions

**Comment by daichengxin** [comment]
#145
