### ISSUE TITLE
AWS tests failing

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/quantms#159]
### Description of the bug

I wanted to run the AWS tests for the release but they are failing.

### System information

Executor AWS batch
Started from nf-tower

**Comment by ypriverol** [comment]
@jpfeuffer How can we help? Can you point to the GitHub actions that is failing?

**Comment by jpfeuffer** [comment]
It is not an action, it is on the nf-core nftower. You need to ask for access.

**Comment by jpfeuffer** [comment]
You won't see anything there since we pipe the logs into files and I am not sure if the workspace is saved.

**Comment by ypriverol** [comment]
Issues related: 
- https://github.com/nf-core/quantms/issues/25
- https://github.com/nf-core/quantms/issues/24
- https://github.com/nf-core/quantms/issues/26
