### ISSUE TITLE
Improvements in the pipeline 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#183]
### Description of feature

In the PR #182 (see unresolved review comments) we found minor issues related with MSstats: 

@qinchunyuan 

- [x] MSstats TMT weird code and import of MSstats. Plus remove the TODO for user contrasts. This should be possible already (double-check)
- [x] Changelog and docu for DIA-NN rework
- [x] double-check usage of empirical vs insilico library in DIA-NN module descriptions

**Comment by daichengxin** [comment]
Hi @ypriverol   Can't I use the plot functions of MSstats in the MSstatsTMT script? even if they are inside the same container.

**Comment by daichengxin** [comment]
MSstatsTMT used MSstats.  https://rdrr.io/bioc/MSstatsTMT/src/R/proteinSummarization.functions.R
