### ISSUE TITLE
DIANN output with Triqler search engine score

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#188]
### Description of feature

@qinchunyuan I'm reviwing some of the DIANN Triqler outputs and I have observed that for some peptides the score is `0.0`, Example: 

```
proteins	peptide	charge	intensity	run	condition	searchScore
RL4_HUMAN	AAAAAAALQAK	2	21465.4	N294-2	lung	0.0
RL4_HUMAN	AAAAAAALQAK	2	31655.7	N295-1	lung	0.0
```

How are you getting those scores? Are those q-values? or probabilities?

**Comment by daichengxin** [comment]
Previously 1 - PEP. Now updated to searchScore= -np.log(Q.value)

**Comment by ypriverol** [comment]
For all DDA and DIA.? @timosachsenberg uses 1-qvalue when exporting triqler in PLFQ. Why we are doing log.

**Comment by ypriverol** [comment]
We should get there as much consistency as possible.

**Comment by daichengxin** [comment]
For DIA. I saw https://github.com/statisticalbiotechnology/dia_sum/blob/main/scripts/result_scripts/diann_output_to_triqler_output.py

**Comment by jpfeuffer** [comment]
No, we are using 1-PEP. Probably Diann does not have probabilities, so they needed to come up with a hack. We should follow their hack for now.
A triqler input of 0 (probability) means q-value of 1, which is fine. It won't really work for good scores, which can have scores higher than 1 now. But maybe triqler can handle this? Or they have another additional transformation after that?
