### ISSUE TITLE
Document parameters with example wiff when provinding mzML in path

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#190]
### Description of feature

When using AB Sciex datasets (.wiff files) the pipeline will be provided with a .wiff file which is not supported by the pipeline. However, if the user provides a `--root_dir` folder with the corresponding mzMLs the pipeline should be able to pick the mzMLs. 

This is also the case when analyzing Thermo experiments, but the user provide already converted files using `--root_dir`.

**Comment by daichengxin** [comment]
Did you provide the `--local_input_type mzML` parameter @ypriverol

**Comment by ypriverol** [comment]
is working !!! Probably we may need to document this better. @daichengxin

**Comment by jpfeuffer** [comment]
Maybe you can set mzML as default.

**Comment by ypriverol** [comment]
Actually, it is a great idea.
