### ISSUE TITLE
Multiple search engine filter peptides (Proteogenomics)

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#198]
### Description of feature

In proteogenomics studies we are probably interested only in peptides that have been identified by `multiple`  search engines (more than one search engine). Do we have a way to filter in ConsensusID for peptides identified with both search engines.

**Comment by jpfeuffer** [comment]
Yes I think it is the -min_support parameter of consensusid

**Comment by ypriverol** [comment]
@da

**Comment by daichengxin** [comment]
ok. @ypriverol

**Comment by ypriverol** [comment]
Is this issue already implemented @daichengxin ?

**Comment by daichengxin** [comment]
yes.
