### ISSUE TITLE
Experimental mass to charge is missing in DIA output report 

### ISSUE THREAD

**Issue by WangHong007** [bigbio/quantms#202]
### Description of the bug

The current DIA-NN used by the pipeline is `v1.8.1`, DIA output lacks experimental mass to charge, and the corresponding column in `DIA-NN v1.8` is `"precursor.mz"`. This deficiency will affect the generation of QC reports.

**Comment by vdemichev** [comment]
A comment: experimental mass to charge might be missing in DIA data (no MS1 signal detected). In fact, DIA data sometimes does not have MS1 at all.
