### ISSUE TITLE
Error pmultiqc with DIA-NN

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#224]
### Description of the bug

-[nf-core/quantms] Pipeline completed with errors-
Error executing process > 'NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)'

Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)` terminated with an error exit status (1)

Command executed:

  multiqc \
      -f \
      --config ./results/multiqc_config.yml \
       \
       \
       \
      --quantification_method feature_intensity \
      ./results \
      -o .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE":
      pmultiqc: $(multiqc --pmultiqc_version | sed -e "s/pmultiqc, version //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  │ ./results/SWATH-TN-9-2.wiff.mzML                                             │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.9/site-packages/multiqc/multiqc.py", line 651 │
  │     output = mod()                                                           │
  │   File "/usr/local/lib/python3.9/site-packages/pmultiqc/modules/quantms/quan │
  │     mt = self.parse_mzml()                                                   │
  │   File "/usr/local/lib/python3.9/site-packages/pmultiqc/modules/quantms/quan │
  │     self.mzml_charge_plot.addValue(charge_state)                             │
  │   File "/usr/local/lib/python3.9/site-packages/pmultiqc/modules/quantms/hist │
  │     self.data[str(value)][stack] += 1                                        │
  │ KeyError: '0'                                                                │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  DEBUG:multiqc:Oops! The 'quantms' MultiQC module broke...
  ================================================================================
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/multiqc/multiqc.py", line 651, in run
      output = mod()
    File "/usr/local/lib/python3.9/site-packages/pmultiqc/modules/quantms/quantms.py", line 147, in __init__
      mt = self.parse_mzml()
    File "/usr/local/lib/python3.9/site-packages/pmultiqc/modules/quantms/quantms.py", line 1002, in parse_mzml
      self.mzml_charge_plot.addValue(charge_state)
    File "/usr/local/lib/python3.9/site-packages/pmultiqc/modules/quantms/histogram.py", line 76, in addValue
      self.data[str(value)][stack] += 1
  KeyError: '0'
  ================================================================================
  |    custom_content | software_versions: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:software_versions: Found 1 sample (html)
  |    custom_content | nf-core-quantms-summary: Found 1 sample (html)
  INFO:multiqc.modules.custom_content.custom_content:nf-core-quantms-summary: Found 1 sample (html)
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Software Versions'.
  DEBUG:multiqc:Reordering sections: anchor 'pmultiqc' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'software_versions' not found for module 'nf-core/quantms Workflow Summary'.
  DEBUG:multiqc:Reordering sections: anchor 'nf-core-quantms-summary' not found for module 'nf-core/quantms Workflow Summary'.
  |           multiqc | Compressing plot data
  INFO:multiqc:Compressing plot data
  |           multiqc | Report      : multiqc_report.html
  INFO:multiqc:Report      : multiqc_report.html
  |           multiqc | Data        : multiqc_data
  INFO:multiqc:Data        : multiqc_data
  DEBUG:multiqc:Moving data file from '/hps/scratch/lsf_tmpdir/hl-codon-130-01/tmp4lcnwp4s/multiqc_data' to './multiqc_data'
  |           multiqc | Plots       : multiqc_plots
  INFO:multiqc:Plots       : multiqc_plots
  DEBUG:multiqc:Moving plots directory from '/hps/scratch/lsf_tmpdir/hl-codon-130-01/tmp4lcnwp4s/multiqc_plots' to './multiqc_plots'
  |           multiqc | MultiQC complete
  INFO:multiqc:MultiQC complete

Work dir:
  /hps/nobackup/juan/pride/reanalysis/dia-projects/PXD014194/work/c3/0d45b625f8cd1564052a84228609fb

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by WangHong007** [comment]
self.mzml_charge_plot = Histogram('Precursor Charge', plot_category='frequency', breaks=[ i for i in range(1, 8)])
@ypriverol The reason for this error may be that the statistical range of charge in pmultiqc is `from 1 to 7`, and here the case where the charge is `0` appears in the spectrum file.

Is it normal for the charge to be 0?

**Comment by ypriverol** [comment]
We have a new error now: 
```
`NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE (1)` terminated with an error exit status (1)

Command executed:

  multiqc \
      -f \
      --config ./results/multiqc_config.yml \
       \
       \
       \
      --quantification_method feature_intensity \
      ./results \
      -o .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:SUMMARYPIPELINE":
      pmultiqc: $(multiqc --pmultiqc_version | sed -e "s/pmultiqc, version //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  │ ./results/SWATH-TN-9-2.wiff.mzML                                             │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 65 │
  │     output = mod()                                                           │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/qua │
  │     mt = self.parse_mzml()                                                   │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/qua │
  │     self.mzml_peak_distribution_plot.addValue(base_peak_intensity)           │
  │   File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/his │
  │     if value < self.threshold:                                               │
  │ TypeError: '<' not supported between instances of 'NoneType' and 'int'       │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  DEBUG:multiqc:Oops! The 'quantms' MultiQC module broke...
  ================================================================================
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 654, in run
      output = mod()
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/quantms.py", line 148, in __init__
      mt = self.parse_mzml()
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/quantms.py", line 1003, in parse_mzml
      self.mzml_peak_distribution_plot.addValue(base_peak_intensity)
    File "/usr/local/lib/python3.10/site-packages/pmultiqc/modules/quantms/histogram.py", line 94, in addValue
      if value < self.threshold:
  TypeError: '<' not supported between instances of 'NoneType' and 'int'
  ================================================================================
```
