### ISSUE TITLE
Publishing `thermorawfileparser` as a standalone module

### ISSUE THREAD

**Issue by lazear** [bigbio/quantms#227]
### Description of feature

Hi,

Is it possible to publish the thermorawfileparser module as a standalone nf-core module? I've just started looking into getting some workflows set up on nf-core, and I'd like to integrate this module - I can always copy/fork it, but it seems like the module might be good for general use as well!

Mike

**Comment by jonasscheid** [comment]
@lazear I saw this one on the nf-core hackathon project board for next week --> https://github.com/orgs/nf-core/projects/47?pane=issue&itemId=38719797

So will be done soon

**Comment by jonasscheid** [comment]
Btw: https://nf-co.re/modules/thermorawfileparser/

**Comment by ypriverol** [comment]
Thanks @jonasscheid .
