### ISSUE TITLE
DIANN and contaminants proteins

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#235]
### Description of the bug

In a recent search using uniprot, I added to DIANN the contaminants database. I got a lot of peptides with no protein associated and also with funny accessions like: `(Bos` . 

- [ ] We need to see if contaminant databases should be attached to the protein database for DIANN? 
- [ ] In case yes, we need to check the structure of the accessions that DIANN consume for contaminant proteins. 
- [ ] We need to remove in the msstats analysis all the contaminants and proteins that are not relevant for the analysis.

**Comment by ypriverol** [comment]
@vdemichev can you give us some feedback here?

**Comment by daichengxin** [comment]
https://github.com/vdemichev/DiaNN/issues/468. This may be relevant. Waiting for feedback

**Comment by vdemichev** [comment]
If a contaminant database is in uniprot format, it will be treated as any other FASTA database. If it's in some unsupported format, then behaviour is undefined. I will need to see how the database looks & how the output looks to comment.
