### ISSUE TITLE
Error in mzmlstatistics

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#267]
### Description of the bug

Error executing process > 'NFCORE_QUANTMS:QUANTMS:FILE_PREPARATION:MZMLSTATISTICS (20220508_EXPL2_Evo7_OOE_DIA21min_InS_R_01_5uL_c_022)'

Caused by:
  Process `NFCORE_QUANTMS:QUANTMS:FILE_PREPARATION:MZMLSTATISTICS (20220508_EXPL2_Evo7_OOE_DIA21min_InS_R_01_5uL_c_022)` terminated with an error exit status (1)

Command executed:

  mzml_statistics.py "20220508_EXPL2_Evo7_OOE_DIA21min_InS_R_01_5uL_c_022.mzML" \
      2>&1 | tee mzml_statistics.log
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_QUANTMS:QUANTMS:FILE_PREPARATION:MZMLSTATISTICS":
      pyopenms: $(pip show pyopenms | grep "Version" | awk -F ': ' '{print $2}')
  END_VERSIONS

Command exit status:
  1

Command output:
  /opt/conda/conda-bld/openms-meta_1652878544517/work/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(131): While loading '20220508_EXPL2_Evo7_OOE_DIA21min_InS_R_01_5uL_c_022.mzML': invalid document structure
  Probable cause: The file suffix (mzML) does not match the file content (unknown). Rename the file to fix this.( in line 1 column 1)
  Traceback (most recent call last):
    File "/hps/nobackup/juan/pride/reanalysis/quantms/bin/mzml_statistics.py", line 66, in <module>
      sys.exit(main())
    File "/hps/nobackup/juan/pride/reanalysis/quantms/bin/mzml_statistics.py", line 62, in main
      mzml_dataframe(mzml_path)
    File "/hps/nobackup/juan/pride/reanalysis/quantms/bin/mzml_statistics.py", line 50, in mzml_dataframe
      mzml_df = parse_mzml(mzml_path, file_columns)
    File "/hps/nobackup/juan/pride/reanalysis/quantms/bin/mzml_statistics.py", line 28, in parse_mzml
      MzMLFile().load(file_name, exp)
    File "pyopenms/pyopenms_2.pyx", line 9531, in pyopenms.pyopenms_2.MzMLFile.load
  RuntimeError: - due to that error of type Parse Error in: /opt/conda/conda-bld/openms-meta_1652878544517/work/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp@132-void OpenMS::Internal::XMLHandler::fatalError(OpenMS::Internal::XMLHandler::ActionMode, const OpenMS::String&, OpenMS::UInt, OpenMS::UInt) const

Command wrapper:
      done < <(ps -e -o pid= -o ppid=)
  
      pstat() {
          local x_pid=$1
          local STATUS=$(2> /dev/null < /proc/$1/status egrep 'Vm|ctxt')
  
          if [ $? = 0 ]; then
          local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
          local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
          local x_peak=$(echo "$STATUS" | egrep 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
          local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
          local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
          local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
          cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
          fi
      }
  
      pwalk() {
          pstat $1
          for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
      }
  
      pwalk $1
  }
  
  nxf_stat() {
      cpu_stat=()
      nxf_tree $1
  
  
  (... more ...)
  ------------------------------------------------------------
  
  Exited with exit code 1.
  
  Resource usage summary:
  
      CPU time :                                   14.00 sec.
      Max Memory :                                 56 MB
      Average Memory :                             48.67 MB
      Total Requested Memory :                     30720.00 MB
      Delta Memory :                               30664.00 MB
      Max Swap :                                   -
      Max Processes :                              14
      Max Threads :                                117
      Run time :                                   5 sec.
      Turnaround time :                            9 sec.
  
  The output (if any) is above this job summary.

Work dir:
  /hps/nobackup/juan/pride/reanalysis/absolute-expression/platelet/PXD037340/work/e1/c94c6eec372e4f155da9365b651079

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

### Relevant files

Important files: 

- Submission: https://ftp.pride.ebi.ac.uk/pride/data/archive/2022/12/PXD037340/
- File: https://ftp.pride.ebi.ac.uk/pride/data/archive/2022/12/PXD037340/20220508_EXPL2_Evo7_OOE_DIA21min_InS_R_01_5uL_c_022.raw

**Comment by jpfeuffer** [comment]
do you have the mzml as well?

**Comment by ypriverol** [comment]
I was actually a filesystem error.
