### ISSUE TITLE
ITRAQ support 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#269]
### Description of feature

We should extend quantms to support Itraq datasets:
- supoort itraq in sdrf annotations
- extend sdrf pipelines to convert to openms configurations
- extend quantms
- try the following dataset https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=9c3f5d8472c1486a8fceda556598ac94

**Comment by jpfeuffer** [comment]
I don't think it needs a new subworkflow. It will work with the TMT workflow. Just different parameters

**Comment by ypriverol** [comment]
Sorry, I did tag it as a subworkflow, but is not (as you said). Hong Wang and Dai are now testing. They did a first iteration yesterday, and it works, but they are working in a full experiment.

**Comment by ypriverol** [comment]
Done.
