### ISSUE TITLE
[Question] mz calculation when converting DIANN outputs

### ISSUE THREAD

**Issue by jspaezp** [bigbio/quantms#276]
Hello!

I noticed that in these lines:

https://github.com/bigbio/quantms/blob/7363d9053658ae6d4c9bf9c0ad90bd7425f097a9/bin/diann_convert.py#L115-L117

https://github.com/bigbio/quantms/blob/7363d9053658ae6d4c9bf9c0ad90bd7425f097a9/bin/diann_convert.py#L903-L918

The precursor mz is calculated from the stripped sequence instead of using the modifications.
I was wondering if this is the desired behavior.

Since in my data the modified sequences are expressed as "SM(UniMod:35)EPEPTIDEK", we could try to query the unimod mass.

LMK what you think,
Best!

**Comment by ypriverol** [comment]
@jspaezp is actually a bug. Please feel free to fix it. I will associate this issue with your main PR.

**Comment by jpfeuffer** [comment]
If pyopenms is already imported in the convert.py script you could maybe use that. If you want to go that route, let me know and I might come up with sample code.

**Comment by jspaezp** [comment]
@jpfeuffer thanks for the suggestion, indeed that is how I went for it in my fork.
Here are the changes for that.

https://github.com/TalusBio/quantms/pull/1
