### ISSUE TITLE
Strange issue with SAGE

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#296]
### Description of the bug

@timosachsenberg @jpfeuffer : 

I'm running sage in a large slurm cluster. I found the following error: 

```
 Error: Failed to read parameters from `/tmp/20230929_204028_hl-codon-130-03.ebi.ac.uk_38_1.json`
  
  Caused by:
      invalid value: string "", expected a character at line 10 column 20
  Process '/thirdparty/Sage/sage' did not finish successfully (exit code: ). Please check the log.
  SageAdapter took 3.68 s (wall), 0.07 s (CPU), 0.06 s (system), 0.01 s (user); Peak Memory Usage: 41 MB.

Work dir:
  /hps/nobackup/juan/pride/reanalysis/absolute-expression/tissues/PXD010154/work/24/d76dd53576146900aaac0f6a701a79

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```
@timosachsenberg has enabled me the debug option, which writes into the work directory the same file that is running in `tmp`. **Note** In slurm the tmp folder is destroyed when the job finished, then I don't have access to `/tmp/20230929_204028_hl-codon-130-03.ebi.ac.uk_38_1.json` (main reason why I asked @timosachsenberg to write also into the working directory of the process ` /hps/nobackup/juan/pride/reanalysis/absolute-expression/tissues/PXD010154/work/24/d76dd53576146900aaac0f6a701a79`). However, when I when to the directory I saw the following file only for config: 

`20230929_204028_hl-codon-130-03.ebi.ac.uk_38_2.json`. See that they are different in the `_1` -> `_2`. I try to find the file `20230929_204028_hl-codon-130-03.ebi.ac.uk_38_1.json` in my **work** directory in nextflow but is not found. What do you think could be the issue. BTW, this only happens for this project now. I have run SAGE with other project and it works.

**Comment by ypriverol** [comment]
This is the Sage configuration file `20230929_204028_hl-codon-130-03.ebi.ac.uk_38_2.json` in case is also wrong: 

```
{
  "database": {
    "bucket_size": 8192,
    "enzyme": {
      "missed_cleavages": 2,
      "min_len": 6,
      "max_len": 40,
      "cleave_at": "KR",
      "restrict": "",
      "c_terminal": true
    },
    "fragment_min_mz": 200.0,
    "fragment_max_mz": 2000.0,
    "peptide_min_mass": 500.0,
    "peptide_max_mass": 5000.0,
    "ion_kinds": ["b", "y"],
    "min_ion_index": 2,
    "static_mods": {
      "C": 57.021464000000002
    },
    "variable_mods": {
      "[M": -131.04048499999999,
"M": 15.994915000000001,
"N": 0.984016,
"Q": 0.984016,
"[": 42.010565
    },
    "max_variable_mods": 3,
    "generate_decoys": false,
    "decoy_tag": "DECOY_"
  },
  "precursor_tol": {
    "ppm": [
      -40.0,
      40.0
    ]
  },
  "fragment_tol": {
    "ppm": [
    -10.0,
    10.0
    ]
  },
  "precursor_charge": [
    2, 5
  ],
  "isotope_errors": [
    0,1
  ],
  "deisotope": false,
  "chimera": false,
  "wide_window": false,
  "predict_rt": false,
  "min_peaks": 1,
  "max_peaks": 500,
  "min_matched_peaks": 1,
  "report_psms": 1
}
```
The line 10 is **restrict**. BTW, Im using here Trypsin/P . I ran this project before with Trypsin and it works.

**Comment by jpfeuffer** [comment]
I guess the way the adapter specifies restrict is wrong. It probably needs to be omitted when empty.
If it's specified it probably always expects some character(s)

**Comment by timosachsenberg** [comment]
k I can fix that

**Comment by ypriverol** [comment]
To make sure if the enzyme is `Trypsin/P` -> `restrict: "P"`

**Comment by jpfeuffer** [comment]
True, and what if you want to restrict on multiple AAs? Is there such an enzyme? Maybe open a bug/feature request in sage?
