### ISSUE TITLE
analysis of DIA runs fails

### ISSUE THREAD

**Issue by jayieh** [bigbio/quantms#311]
### Description of the bug

I am trying to run quantms on a DIA dataset - acquired on an Exploris 480, with raw files converted to mzML.

I am using N E X T F L O W  ~  version 23.10.0

with
```
-profile singularity
--acquisition_method dia
```

the option is recognized by nf, asI see the following promt:

`Input/output options

  acquisition_method             : dia`

The pipeline starts running and MZMLINDEXING is fine, but then the pipeline tries to run comet, rather then diann on those files, throwing the following error:

`ERROR ~ Error executing process > 'NFCORE_QUANTMS:QUANTMS:LFQ:ID:DATABASESEARCHENGINES:SEARCHENGINECOMET`

`- Load spectra: Warning - no spectra searched.`

this happens on a CentOS 7 HPC environment, but also a Ubuntu 22.04.2 LTS (with -profile conda) with this files.

are there any additional parameters to consider for DIA data?

**Comment by ypriverol** [comment]
Hi @jayieh Can you provide the full command you are using and also the configuration file SDRF.

**Comment by jayieh** [comment]
thanks for the quick reply! I will give it a try.
