### ISSUE TITLE
Benchmark skip pre-analysis vs full preanalysis.

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#338]
In a recent PR #335, we introduced the possibility to skip the pre-analysis step. Would be great to have some plots and results about how skipping pre-analysis will affect the final results. @daichengxin maybe reanalyzing one of the benchmark datasets for DIA without the pre-analysis step would be a good idea and share the results in here.

**Comment by daichengxin** [comment]
PXD026600 are used to benchmark. Each concentration has three technical replicates. Three strategies of library generation: 1. all files  2. select a file in each technical replicates group (total 16 file). 3. random sampling 16 files. Performance is indeed degraded, compared to the full library. 

![image](https://github.com/bigbio/quantms/assets/37200167/30c75373-8bcf-4bd1-a241-5fd80c367d9c)
![image](https://github.com/bigbio/quantms/assets/37200167/de81aa3a-a5f6-4a8a-80af-671b1d4d6bc9)
![image](https://github.com/bigbio/quantms/assets/37200167/0ea22bcc-8de9-490e-b01a-5e9df28d0382)

**Comment by ypriverol** [comment]
Results are almost identical.
