### ISSUE TITLE
quantms failing with a big dataset 15K files

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#339]
### Description of the bug

I'm running a big dataset and the diann assembly step fails https://github.com/vdemichev/DiaNN/issues/899. Looks like a memory issue, I have given more than 1.8TB of memory and 48 CPUs. Vadim has suggested using a random number of files only for the library creation, @daichengxin is this related with the previos PR of #335 ?

**Comment by daichengxin** [comment]
Yes. It's releated with library creation. How do we determine random number? or should it be ratio?

**Comment by ypriverol** [comment]
I think it must be a parameter in the first implementation. We only have a few massive datasets like this in fact, working with a previous dataset of 6k files it works this step. Then, I just suggest taking (in this first implementation) a parameter, which can `empirical_assembly_ms_n = 200` and then the user can easily configure it in the commandline. What do you think?

**Comment by ypriverol** [comment]
@daichengxin Im reopening this issue, because the solution still doesn't work. In the current implementation, you selected for the empirical_assemembly a ceratin number of raw files (👌), but in the Assembly step you are passing all the mzMLs; which will not work for any amount of data Im trying with the `empirical_assembly_ms_n`. I have try 10 files but then in the assembly step all the raw files are used an even If I go for 1TB of memory, the tool fails. What are the options here @daichengxin @vdemichev

```
{all_mzml} \
        --lib lib.predicted.speclib \
        --threads 24 \
        --out-lib empirical_library.tsv \
        --verbose 3 \
        --rt-profiling \
        --temp ./quant/ \
        --use-quant \
        --quick-mass-acc --individual-mass-acc \
        --individual-windows \
        --gen-spec-lib \
         \
        2>&1 | tee assemble_empirical_library.log
```

**Comment by vdemichev** [comment]
"but then in the assembly step all the raw files are used" - the idea would be to not use all raw files for empirical library generation

**Comment by jspaezp** [comment]
is this fixed in point 3 of this PR -> https://github.com/bigbio/quantms/pull/355 ?

**Comment by ypriverol** [comment]
Yes this issue is fixed. Let me close it, to remove confusion.
