### ISSUE TITLE
Extracting tar archives of Bruker .d folders sometimes fails silently.

### ISSUE THREAD

**Issue by wfondrie** [bigbio/quantms#395]
### Description of the bug

We've observed that extracting tar archives of Bruker .d folders will sometimes fail silently - the `NFCORE_QUANTMS:QUANTMS:FILE_PREPARATION:DECOMPRESS` will succeed, but the results extracted .d will be missing one or more files. This seems to occur randomly and often deleting the cached version and rerunning the workflow will solve it. 

I propose adding a verification that the extracted folder matches the archive in the function here: https://github.com/bigbio/quantms/blob/85f04b84c1ef77ba29e83781d077d87b62397d9f/modules/local/decompress_dotd/main.nf#L42-L58

Specifically, I would change line 50:
```bash
                     *.tar)       tar xvf \$1     ;; 
```
to:
```bash
                     *.tar)       tar xvf \$1 && tar df \$1 \$(basename \$1 .tar)     ;; 
```

We could also add this to the `tar.gz` extraction as well.

Let me know what you think and I'm happy to put in a PR.

**Comment by ypriverol** [comment]
@wfondrie do you think someone from your team can take this issue?

**Comment by wfondrie** [comment]
Absolutely - I'm happy to put in a PR here.
