### ISSUE TITLE
Allow missing fractions 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#48]
We need to allow missing fractions in the data analysis when a fraction is not relevant for the study. Issue https://github.com/ypriverol/quantms-research/issues/5. @timosachsenberg

**Comment by daichengxin** [comment]
Yes.proteomicslfq requires fractions to be continuous, so I modified the sdrf file to make them continuous. Maybe it is better to automatically correct this problem when checking sdrf or expdesign？

**Comment by daichengxin** [comment]
https://github.com/multiomics/multiomics-configs/pull/44/files. I remember to modify the sdrf file to make them continuous when have missing fractions. Can you check the sdrf file you used again @ypriverol ?

**Comment by ypriverol** [comment]
Ok. Doesn't matter if the fractions are consecutive. IF one sample has 24 fractions and the other 23. plfq will fail.

**Comment by ypriverol** [comment]
This is solved.
