### ISSUE TITLE
Change check_samplesheet.py to validate SDRF

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/quantms#5]

**Comment by daichengxin** [comment]
In this file, use sdrf-pipelines package to validate SDRF. What do you think ? @jpfeuffer @ypriverol

**Comment by ypriverol** [comment]
You can do it. But I think @jpfeuffer that `check_samplesheet` can be replaced by the sdrf check command. We should remove as much as possible everything that is not needed. A module based on `sdrf validator` can help to validate the file.

**Comment by jpfeuffer** [comment]
I would vote for the opposite.
Try to follow nf-core standards as much as possible.

Who knows what they are going to use it for. E.g. for interaction with nftower etc.

So I would vote for using the sdrf check command/package inside that file.

**Comment by ypriverol** [comment]
I understand now, you are right

**Comment by daichengxin** [comment]
Got it. I follow @jpfeuffer
