### ISSUE TITLE
Make the file_id (to combine e.g. after consensusID) based on the basename of the input file

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/quantms#62]
### Description of feature

Instead of the hash that we are currently using.
This would result in easier readable files than 261789bbc5e17774250b0b6656dd0696_consensus.idXML 
But I am not sure what implications this has for caching the workflow. I guess it should be fine.

**Comment by ypriverol** [comment]
@qinchunyuan is this issue has been solved?

**Comment by daichengxin** [comment]
Yes
