### ISSUE TITLE
quantms error with sdrf latest versions 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#66]
### Description of feature

The recent version of `sdrf-pipelines` fails for the following SDRF in multiomics `PXD008440.sdrf.tsv` with an error empty columns values, which is not the case.

**Comment by daichengxin** [comment]
![image](https://user-images.githubusercontent.com/37200167/151960536-ce3e4179-85a8-405c-a0c2-12c0db7342b0.png)
there are some `nan` values in PXD008440.sdrf.tsv.

**Comment by jpfeuffer** [comment]
@ypriverol is this solved?

**Comment by ypriverol** [comment]
I changed the nan -> non available 😂

**Comment by timosachsenberg** [comment]
is it solved?
