### ISSUE TITLE
Do we need multiQC?

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/quantms#74]
### Description of feature

We already have pmultiQC. Do we need multiQC to run pmultiQC or something?
If not, remove it.

**Comment by jpfeuffer** [comment]
@daichengxin the idea would be to only have pMultiQC and send an email with the report, like multiqc does.

**Comment by daichengxin** [comment]
Good idea. I am trying to inplement these functions in pmultiqc

**Comment by jpfeuffer** [comment]
I don't think you need to implement it in pMultiQC but you need to use pMultiQC in the place of multiQC and set the nextflow variables that define the report to be be emailed to the output of pMultiQC instead

**Comment by daichengxin** [comment]
Yes. I am sending a example  in slack, and removing multiqc.

**Comment by daichengxin** [comment]
done #82
