### ISSUE TITLE
quantms subworkflows to be built

### ISSUE THREAD

**Issue by daichengxin** [bigbio/quantms#8]
## What subworkflow to be built? such as QC?

`DecoyDatabase` and `OpenmsPeakpicker` should be called as single module.

**Comment by ypriverol** [comment]
The next subworkflows: 

- [ ] `DatabaseSearchEngines` including the following processes: `process search_engine_msgf`, `process search_engine_comet`
- [ ] `index_peptides`: Could be a single module that can be reuse multiple times. 
- [ ] `PercolatorPeptideIdBoost` including the following processes: `extract_percolator_features`, `percolator`
- [ ] `PSMFDRControl` including the following processes: `fdr_idpep`, `idpep`, `idscoreswitcher_to_qval`, `consensusid `, `fdr_consensusid`, `idfilter`
- [ ] `PhosphoScoring` including the following processes: `idscoreswitcher_for_luciphor`, `luciphor` 
- [ ] `ProteinInference` including `idemapper`, `file_merge `, `protein_epifany`, `protein_inference`, `epi_filter `, `resolve_conflict `
- [ ] `ProteinQuant` including  `pro_quant`, `MsstatsConverter `
- [ ] `pmultiqc` should be a single module. 

What do you think about this proposal @daichengxin @jpfeuffer ?

**Comment by ypriverol** [comment]
I think `index_peptides` can be the end of the `DatabaseSearchEngines` subworkflow because all the time will be needed.

**Comment by daichengxin** [comment]
`DatabaseSearchEngines` is ok. And they shared parameters. `PercolatorPeptideIdBoost `is also ok, they have close relationship. `PSMFDRControl` seem to have too many modules. `idfilter` could be a single module that can be reuse in `ProteinInference`. `PhosphoScoring` is ok. `idemapper `and `file_merge` seem to have no direct relationship with protein inference. `idemapper ` should be with `isobaricanalyzer`.  `file_merge ` can be a single module. `ProteinQuant` and `pmultiqc` are ok.

**Comment by jpfeuffer** [comment]
I would do: 

- [ ] `DatabaseSearchEngines` including the following processes: `process search_engine_msgf`, `process search_engine_comet` and `index_peptides` (starting from 2.7.1, indexing is done internally per default anyway)
- [ ] `PSMRescoring` including the following processes: `extract_percolator_features`, `percolator`, `fdr_idpep`, `idpep`
- [ ] `ConsensusID` could also be a single module
- [ ] `PSMFDRControl` including the following processes: `idscoreswitcher_to_qval` (if IDPEP was chosen), `fdr_consensusid` (if consensusID was used), `idfilter`
- [ ] `PhosphoScoring` including the following processes: `idscoreswitcher_for_luciphor`, `luciphor` 
- [ ] `IDMapper` could be a single module
- [ ] `FileMerge`could be a single module
- [ ] `ProteinInference` including `protein_epifany`, `protein_inference`, `epi_filter `
- [ ] `ProteinQuant` including  `resolve_conflict `, `pro_quant`, `MsstatsConverter `
- [ ] `pmultiqc` should be a single module.

**Comment by ypriverol** [comment]
Looks like a great strategy. I will open independent issues.

**Comment by daichengxin** [comment]
`Isobaricanalyzer ` could be with IDmapper ? In LFQ, there is no `IDMapper`

**Comment by jpfeuffer** [comment]
Yes could be together, in LFQ this happens in the ProteomicsLFQ step.

**Comment by ypriverol** [comment]
@daichengxin if everyone agreed with @jpfeuffer https://github.com/bigbio/quantms/issues/8#issuecomment-963098866 we should do a PR by subworkflow.

**Comment by ypriverol** [comment]
Done.
