### ISSUE TITLE
Subworkflow for search 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/quantms#9]
## DatabaseSearchEngines 

Including the following processes: process search_engine_msgf, process search_engine_comet and index_peptides (starting from 2.7.1, indexing is done internally per default anyway)

**Comment by jpfeuffer** [comment]
Channels: 
takes: mzml_id, mzmls, per_file_settings
outputs: mzml_id, idxmls

Global params:
needs: params.searchengines, and any setting not defined by the sdrf
could set: nr_searchengines

**Comment by ypriverol** [comment]
done
